-- HYRSPACE v4 database
create table if not exists public.profiles (
  id uuid primary key references auth.users(id) on delete cascade,
  username text not null unique,
  about text not null default '',
  avatar_url text not null default '',
  role text not null default 'Пользователь',
  created_at timestamptz not null default now(),
  constraint profiles_role_check check (role in (
    'Пользователь','VIP','Администратор','Мем Года','Модератор','Разработчик','Дизайнер','Геймер','Мемолог','Легенда',
    'OG','Premium','Контентмейкер','Музыкант','Фотограф','Гений','Сигма','Топ','Активист','Верифицирован'
  ))
);

create table if not exists public.posts (
  id bigint generated by default as identity primary key,
  author_id uuid not null references public.profiles(id) on delete cascade,
  body text not null check (char_length(body) between 1 and 5000),
  created_at timestamptz not null default now()
);

create table if not exists public.post_comments (
  id bigint generated by default as identity primary key,
  post_id bigint not null references public.posts(id) on delete cascade,
  author_id uuid not null references public.profiles(id) on delete cascade,
  body text not null check (char_length(body) between 1 and 1000),
  created_at timestamptz not null default now()
);

create table if not exists public.post_likes (
  post_id bigint not null references public.posts(id) on delete cascade,
  user_id uuid not null references public.profiles(id) on delete cascade,
  created_at timestamptz not null default now(),
  primary key (post_id, user_id)
);

create table if not exists public.followers (
  follower_id uuid not null references public.profiles(id) on delete cascade,
  following_id uuid not null references public.profiles(id) on delete cascade,
  created_at timestamptz not null default now(),
  primary key (follower_id, following_id),
  constraint no_self_follow check (follower_id <> following_id)
);

create table if not exists public.groups (
  id bigint generated by default as identity primary key,
  name text not null check (char_length(name) between 2 and 80),
  description text not null default '',
  avatar_url text not null default '',
  is_private boolean not null default false,
  owner_id uuid not null references public.profiles(id) on delete cascade,
  created_at timestamptz not null default now()
);

create table if not exists public.group_members (
  group_id bigint not null references public.groups(id) on delete cascade,
  user_id uuid not null references public.profiles(id) on delete cascade,
  role text not null default 'member' check (role in ('owner','admin','member')),
  joined_at timestamptz not null default now(),
  primary key (group_id, user_id)
);

create table if not exists public.group_messages (
  id bigint generated by default as identity primary key,
  group_id bigint not null references public.groups(id) on delete cascade,
  author_id uuid not null references public.profiles(id) on delete cascade,
  body text not null check (char_length(body) between 1 and 3000),
  created_at timestamptz not null default now()
);

create table if not exists public.notifications (
  id bigint generated by default as identity primary key,
  user_id uuid not null references public.profiles(id) on delete cascade,
  actor_id uuid references public.profiles(id) on delete set null,
  type text not null check (type in ('follow','like','comment','group_invite')),
  post_id bigint references public.posts(id) on delete cascade,
  group_id bigint references public.groups(id) on delete cascade,
  text text not null,
  is_read boolean not null default false,
  created_at timestamptz not null default now()
);

create index if not exists posts_created_idx on public.posts(created_at desc);
create index if not exists comments_post_idx on public.post_comments(post_id, created_at);
create index if not exists messages_group_idx on public.group_messages(group_id, created_at);
create index if not exists followers_following_idx on public.followers(following_id);

alter table public.profiles enable row level security;
alter table public.posts enable row level security;
alter table public.post_comments enable row level security;
alter table public.post_likes enable row level security;
alter table public.followers enable row level security;
alter table public.groups enable row level security;
alter table public.group_members enable row level security;
alter table public.group_messages enable row level security;
alter table public.notifications enable row level security;

-- Helper: admin check. First admin must be set manually once in SQL Editor.
create or replace function public.is_admin(uid uuid default auth.uid())
returns boolean language sql stable security definer set search_path = public
as $$ select exists(select 1 from public.profiles where id = uid and role = 'Администратор'); $$;

-- Profile trigger
create or replace function public.handle_new_user()
returns trigger language plpgsql security definer set search_path = public
as $$
begin
  insert into public.profiles(id, username, about, avatar_url)
  values (
    new.id,
    left(coalesce(nullif(new.raw_user_meta_data->>'username',''), 'user_' || left(new.id::text,8)), 32),
    coalesce(new.raw_user_meta_data->>'about',''),
    coalesce(new.raw_user_meta_data->>'avatar_url','')
  ) on conflict (id) do nothing;
  return new;
end; $$;

drop trigger if exists on_auth_user_created on auth.users;
create trigger on_auth_user_created after insert on auth.users for each row execute function public.handle_new_user();

-- Policies
 drop policy if exists profiles_select on public.profiles;
create policy profiles_select on public.profiles for select using (true);
 drop policy if exists profiles_insert on public.profiles;
create policy profiles_insert on public.profiles for insert to authenticated with check (id = auth.uid());
 drop policy if exists profiles_update on public.profiles;
create policy profiles_update on public.profiles for update to authenticated using (id = auth.uid()) with check (id = auth.uid());

 drop policy if exists posts_select on public.posts;
create policy posts_select on public.posts for select using (true);
 drop policy if exists posts_insert on public.posts;
create policy posts_insert on public.posts for insert to authenticated with check (author_id = auth.uid());
 drop policy if exists posts_delete on public.posts;
create policy posts_delete on public.posts for delete to authenticated using (author_id = auth.uid() or public.is_admin());

 drop policy if exists comments_select on public.post_comments;
create policy comments_select on public.post_comments for select using (true);
 drop policy if exists comments_insert on public.post_comments;
create policy comments_insert on public.post_comments for insert to authenticated with check (author_id = auth.uid());
 drop policy if exists comments_delete on public.post_comments;
create policy comments_delete on public.post_comments for delete to authenticated using (author_id = auth.uid() or public.is_admin());

 drop policy if exists likes_select on public.post_likes;
create policy likes_select on public.post_likes for select using (true);
 drop policy if exists likes_insert on public.post_likes;
create policy likes_insert on public.post_likes for insert to authenticated with check (user_id = auth.uid());
 drop policy if exists likes_delete on public.post_likes;
create policy likes_delete on public.post_likes for delete to authenticated using (user_id = auth.uid());

 drop policy if exists follows_select on public.followers;
create policy follows_select on public.followers for select using (true);
 drop policy if exists follows_insert on public.followers;
create policy follows_insert on public.followers for insert to authenticated with check (follower_id = auth.uid());
 drop policy if exists follows_delete on public.followers;
create policy follows_delete on public.followers for delete to authenticated using (follower_id = auth.uid());

-- Groups
 drop policy if exists groups_select on public.groups;
create policy groups_select on public.groups for select using (not is_private or owner_id = auth.uid() or exists(select 1 from public.group_members gm where gm.group_id = id and gm.user_id = auth.uid()));
 drop policy if exists groups_insert on public.groups;
create policy groups_insert on public.groups for insert to authenticated with check (owner_id = auth.uid());
 drop policy if exists groups_update on public.groups;
create policy groups_update on public.groups for update to authenticated using (owner_id = auth.uid()) with check (owner_id = auth.uid());
 drop policy if exists groups_delete on public.groups;
create policy groups_delete on public.groups for delete to authenticated using (owner_id = auth.uid() or public.is_admin());

 drop policy if exists members_select on public.group_members;
create policy members_select on public.group_members for select using (user_id = auth.uid() or exists(select 1 from public.group_members gm where gm.group_id = public.group_members.group_id and gm.user_id = auth.uid()));
 drop policy if exists members_insert on public.group_members;
create policy members_insert on public.group_members for insert to authenticated with check (
  user_id = auth.uid() or exists(select 1 from public.group_members gm where gm.group_id = public.group_members.group_id and gm.user_id = auth.uid() and gm.role in ('owner','admin'))
);
 drop policy if exists members_update on public.group_members;
create policy members_update on public.group_members for update to authenticated using (exists(select 1 from public.group_members gm where gm.group_id = public.group_members.group_id and gm.user_id = auth.uid() and gm.role = 'owner'));
 drop policy if exists members_delete on public.group_members;
create policy members_delete on public.group_members for delete to authenticated using (user_id = auth.uid() or exists(select 1 from public.group_members gm where gm.group_id = public.group_members.group_id and gm.user_id = auth.uid() and gm.role in ('owner','admin')));

 drop policy if exists messages_select on public.group_messages;
create policy messages_select on public.group_messages for select using (exists(select 1 from public.group_members gm where gm.group_id = group_id and gm.user_id = auth.uid()));
 drop policy if exists messages_insert on public.group_messages;
create policy messages_insert on public.group_messages for insert to authenticated with check (author_id = auth.uid() and exists(select 1 from public.group_members gm where gm.group_id = group_id and gm.user_id = auth.uid()));
 drop policy if exists messages_delete on public.group_messages;
create policy messages_delete on public.group_messages for delete to authenticated using (author_id = auth.uid() or public.is_admin());

 drop policy if exists notifications_select on public.notifications;
create policy notifications_select on public.notifications for select to authenticated using (user_id = auth.uid());
 drop policy if exists notifications_update on public.notifications;
create policy notifications_update on public.notifications for update to authenticated using (user_id = auth.uid()) with check (user_id = auth.uid());


create or replace function public.protect_profile_role()
returns trigger language plpgsql security definer set search_path = public
as $$
begin
  if not public.is_admin(auth.uid()) and new.role <> old.role then
    new.role := old.role;
  end if;
  return new;
end; $$;

drop trigger if exists protect_profile_role on public.profiles;
create trigger protect_profile_role before update on public.profiles for each row execute function public.protect_profile_role();

-- RPCs for safe privileged actions
create or replace function public.admin_set_role(target_user uuid, new_role text)
returns void language plpgsql security definer set search_path = public
as $$ begin
  if not public.is_admin(auth.uid()) then raise exception 'Only administrators can change roles'; end if;
  if new_role not in ('Пользователь','VIP','Администратор','Мем Года','Модератор','Разработчик','Дизайнер','Геймер','Мемолог','Легенда','OG','Premium','Контентмейкер','Музыкант','Фотограф','Гений','Сигма','Топ','Активист','Верифицирован') then raise exception 'Invalid role'; end if;
  update public.profiles set role = new_role where id = target_user;
end; $$;

grant execute on function public.admin_set_role(uuid,text) to authenticated;

grant select on public.profiles, public.posts, public.post_comments, public.post_likes, public.followers to anon, authenticated;
grant insert, update on public.profiles to authenticated;
grant select, insert, delete on public.posts, public.post_comments, public.post_likes, public.followers to authenticated;
grant select, insert, update, delete on public.groups, public.group_members, public.group_messages, public.notifications to authenticated;

-- Realtime for chat/feeds
alter publication supabase_realtime add table public.group_messages;
alter publication supabase_realtime add table public.posts;
alter publication supabase_realtime add table public.post_comments;
