-- HYRSPACE v3
-- Выполни этот SQL целиком в Supabase SQL Editor.

create table if not exists public.profiles (
  id uuid primary key references auth.users(id) on delete cascade,
  username text not null unique,
  about text not null default '',
  avatar_url text not null default '',
  role text not null default 'Пользователь',
  created_at timestamptz not null default now(),
  constraint profiles_role_check check (
    role in ('Пользователь','VIP','Мем Года','Администратор')
  )
);

create table if not exists public.posts (
  id bigint generated by default as identity primary key,
  author_id uuid not null references auth.users(id) on delete cascade,
  text text not null check (char_length(text) between 1 and 2000),
  created_at timestamptz not null default now()
);

create table if not exists public.post_comments (
  id bigint generated by default as identity primary key,
  post_id bigint not null references public.posts(id) on delete cascade,
  author_id uuid not null references auth.users(id) on delete cascade,
  author_name text not null,
  text text not null check (char_length(text) between 1 and 500),
  created_at timestamptz not null default now()
);

alter table public.profiles enable row level security;
alter table public.posts enable row level security;
alter table public.post_comments enable row level security;

grant select on public.profiles to anon, authenticated;
grant insert, update on public.profiles to authenticated;

grant select, insert, delete on public.posts to authenticated;

grant select, insert, delete on public.post_comments to authenticated;

drop policy if exists "profiles read" on public.profiles;
create policy "profiles read" on public.profiles for select
to anon, authenticated using (true);

drop policy if exists "own profile insert" on public.profiles;
create policy "own profile insert" on public.profiles for insert
to authenticated with check ((select auth.uid()) = id);

drop policy if exists "own profile update" on public.profiles;
create policy "own profile update" on public.profiles for update
to authenticated
using ((select auth.uid()) = id)
with check ((select auth.uid()) = id);

drop policy if exists "posts read" on public.posts;
create policy "posts read" on public.posts for select
to authenticated using (true);

drop policy if exists "own post insert" on public.posts;
create policy "own post insert" on public.posts for insert
to authenticated
with check ((select auth.uid()) = author_id);

drop policy if exists "own post delete" on public.posts;
create policy "own post delete" on public.posts for delete
to authenticated
using ((select auth.uid()) = author_id);

drop policy if exists "post comments read" on public.post_comments;
create policy "post comments read" on public.post_comments for select
to authenticated using (true);

drop policy if exists "post comments insert" on public.post_comments;
create policy "post comments insert" on public.post_comments for insert
to authenticated
with check ((select auth.uid()) = author_id);

drop policy if exists "own comment delete" on public.post_comments;
create policy "own comment delete" on public.post_comments for delete
to authenticated
using ((select auth.uid()) = author_id);

-- Автоматическое создание профиля после регистрации.
create or replace function public.handle_new_user()
returns trigger
language plpgsql
security definer set search_path = public
as $$
begin
  insert into public.profiles (id, username)
  values (
    new.id,
    coalesce(new.raw_user_meta_data->>'username', 'user_' || left(new.id::text, 8))
  )
  on conflict (id) do nothing;
  return new;
end;
$$;

drop trigger if exists on_auth_user_created on auth.users;
create trigger on_auth_user_created
after insert on auth.users
for each row execute function public.handle_new_user();
create table if not exists public.profiles (
  id uuid primary key references auth.users(id) on delete cascade,
  username text not null unique,
  about text not null default '',
  avatar_url text not null default '',
  role text not null default 'Пользователь',
  created_at timestamptz not null default now(),
  constraint profiles_role_check check (
    role in ('Пользователь','VIP','Мем Года','Администратор')
  )
);

create table if not exists public.posts (
  id bigint generated by default as identity primary key,
  author_id uuid not null references auth.users(id) on delete cascade,
  text text not null check (char_length(text) between 1 and 2000),
  created_at timestamptz not null default now()
);

create table if not exists public.post_comments (
  id bigint generated by default as identity primary key,
  post_id bigint not null references public.posts(id) on delete cascade,
  author_id uuid not null references auth.users(id) on delete cascade,
  author_name text not null,
  text text not null check (char_length(text) between 1 and 500),
  created_at timestamptz not null default now()
);

alter table public.profiles enable row level security;
alter table public.posts enable row level security;
alter table public.post_comments enable row level security;

grant select on public.profiles to anon, authenticated;
grant insert, update on public.profiles to authenticated;

grant select, insert, delete on public.posts to authenticated;
grant select, insert, delete on public.post_comments to authenticated;

drop policy if exists "profiles read" on public.profiles;
create policy "profiles read"
on public.profiles
for select
to anon, authenticated
using (true);

drop policy if exists "own profile insert" on public.profiles;
create policy "own profile insert"
on public.profiles
for insert
to authenticated
with check ((select auth.uid()) = id);

drop policy if exists "own profile update" on public.profiles;
create policy "own profile update"
on public.profiles
for update
to authenticated
using ((select auth.uid()) = id)
with check ((select auth.uid()) = id);

drop policy if exists "posts read" on public.posts;
create policy "posts read"
on public.posts
for select
to authenticated
using (true);

drop policy if exists "own post insert" on public.posts;
create policy "own post insert"
on public.posts
for insert
to authenticated
with check ((select auth.uid()) = author_id);

drop policy if exists "own post delete" on public.posts;
create policy "own post delete"
on public.posts
for delete
to authenticated
using ((select auth.uid()) = author_id);

drop policy if exists "post comments read" on public.post_comments;
create policy "post comments read"
on public.post_comments
for select
to authenticated
using (true);

drop policy if exists "post comments insert" on public.post_comments;
create policy "post comments insert"
on public.post_comments
for insert
to authenticated
with check ((select auth.uid()) = author_id);

drop policy if exists "own comment delete" on public.post_comments;
create policy "own comment delete"
on public.post_comments
for delete
to authenticated
using ((select auth.uid()) = author_id);

create or replace function public.handle_new_user()
returns trigger
language plpgsql
security definer set search_path = public
as $$
begin
  insert into public.profiles (id, username)
  values (
    new.id,
    coalesce(
      new.raw_user_meta_data->>'username',
      'user_' || left(new.id::text, 8)
    )
  )
  on conflict (id) do nothing;

  return new;
end;
$$;

drop trigger if exists on_auth_user_created on auth.users;

create trigger on_auth_user_created
after insert on auth.users
for each row
execute function public.handle_new_user();
